SELECT*from students;
SELECT*from courses;
SELECT*from enrollments;

--Show course names along with enrolled student names.
SELECT c.course_name,s.student_name 
FROM enrollments as e
JOIN courses as c 
    on e.course_id=c.course_id
JOIN students as s 
    on e.student_id=s.student_id;
--Find how many students enrolled in each course.
select c.course_name,count(e.student_id) as no_of_students
from courses as c
JOIN enrollments as e 
on c.course_id=e.course_id
group by course_name;
--Find total revenue generated by each course
select c.course_name, (c.price*count(e.course_id)) as total_price
from courses as c 
JOIN enrollments as e 
ON c.course_id=e.course_id
group by course_name;
--Find courses with n0 enrolled in yet.
SELECT c.course_name
FROM courses as c 
left join enrollments as e 
on c.course_id=e.course_id
where e.enrollment_id is NULL;
--Find students who have enrolled in more than 1 course.
SELECT s.student_name as student_enrolled_more_than_one_course
FROM enrollments as e
join students as s 
    on e.student_id=s.student_id
group by s.student_name
HAVING count(e.course_id)>1;
--Find course categories that have more than 3 total enrollments.
select category,count(e.enrollment_id) as total_enrollments
from courses as c 
join enrollments as e 
on c.course_id=e.course_id
group by c.category
having count(e.enrollment_id)>3
order by c.course_id;
--Find students who have completed at least one course.
select s.student_name,count(c.course_id) as no_of_courses
FROM students as s
JOIN enrollments as e
    on s.student_id=e.student_id
join courses as c
    on c.course_id=e.course_id
group by s.student_name
HAVING count(c.course_id)>=1;
--Find the course that generated the highest revenue.
SELECT c.course_name,sum(c.price)as total_revenue
from courses as c 
join enrollments as e
    on c.course_id=e.course_id
WHERE c.price is not NULL  --null handling is used here 
group by c.course_id,c.course_name
ORDER by total_revenue DESC
limit 1;
--Find students who never enrolled in any course.
select student_name 
FROM students 
where student_id not in (
select student_id from enrollments);
--Find total revenue generated country-wise.
SELECT s.country,sum(c.price) as revenue
FROM students as s
join enrollments as e
    on s.student_id = e.student_id 
join courses as c
    on c.course_id=e.course_id
group by country;