--Show course names along with enrolled student names.
SELECT c.course_name,s.student_name 
FROM enrollments as e
JOIN courses as c 
    on e.course_id=c.course_id
JOIN students as s 
    on e.student_id=s.student_id;
--Find how many students enrolled in each course.
select c.course_name,count(e.student_id) as no_of_students
from courses as c
JOIN enrollments as e 
on c.course_id=e.course_id
group by course_name;
--Find total revenue generated by each course
select c.course_name, (c.price*count(e.course_id)) as total_price
from courses as c 
JOIN enrollments as e 
ON c.course_id=e.course_id
group by course_name;
--Find courses with n0 enrolled in yet.
SELECT c.course_name
FROM courses as c 
left join enrollments as e 
on c.course_id=e.course_id
where e.enrollment_id is NULL;
--Find students who have enrolled in more than 1 course.
SELECT s.student_name as student_enrolled_more_than_one_course
FROM enrollments as e
join students as s 
    on e.student_id=s.student_id
group by s.student_name
HAVING count(e.course_id)>1;
--Find course categories that have more than 3 total enrollments.
select category,count(e.enrollment_id) as total_enrollments
from courses as c 
join enrollments as e 
on c.course_id=e.course_id
group by c.category
having count(e.enrollment_id)>3
order by c.course_id;


